package org.andarted.hnefatafl.model;

public enum AreaType {
	COMMONS,
	
	NORTH_WALL,
	NORTH_FIELD,
	EAST_WALL,
	EAST_FIELD,
	SOUTH_WALL,
	SOUTH_FIELD,
	WEST_WALL,
	WEST_FIELD,
	
	THRONE_NORTH_ATTACK,
	THRONE_NORTH_SQUARE,
	THRONE_EAST_ATTACK,
	THRONE_EAST_SQUARE,
	THRONE_SOUTH_ATTACK,
	THRONE_SOUTH_SQUARE,
	THRONE_WEST_ATTACK,
	THRONE_WEST_SQUARE,
	
	THRONE_WITH_KING,
	THRONE_WITHOUT_KING;

}
