package org.andarted.hnefatafl.model;

public enum SquareType {
	EMPTY,
	THRONE,
	ESCAPE,
	MOUSE_HOVER,
	HIGHLIGHTED,
	HIGHLIGHTED_ORIGIN,
	HIGHLIGHTED_XAXIS,
	HIGHLIGHTED_YAXIS,
	HIGHLIGHTED_PLANE,
	ANARCHIST_DEATH_ZONE,
	ROYALIST_DEATH_ZONE,
	SQUARE_ERROR;
}
